/**
 * Patient closing screen (plan §5): trend + next step + closure, or the emergency line alone.
 * Lines are fixed in content/patient-lines.json; never generated by a model. Never shows a score.
 */
import lines from "@/content/patient-lines.json"
import type { Recommendation, Trend } from "@/lib/types"

export type ClosingInput = {
  trend: Trend | "first" | "finished_early"
  recommendation: Recommendation | "finished_early"
  redFlag: boolean
  clinicName: string
}

export function closingLines({ trend, recommendation, redFlag, clinicName }: ClosingInput): string[] {
  if (redFlag) return [lines.emergency]
  const next =
    recommendation === "human_confirm" ? lines.next_step.finished_early : lines.next_step[recommendation]
  return [lines.trend[trend], next.replace("{clinic}", clinicName), lines.closure]
}
